[package]
edition = "2024"
name = "rtc"
version = "0.1.0"

[dependencies]
# NOTE: A clock rate of 1 kHz is required for the RTC clock mode
shared-metro = {path = "../../lib/shared-metro", features = ["clock1k"]}
