[package]
edition = "2021"
# This cannot simply be named `aes` due to the dependency with the same name.
name = "aes-test"
version = "0.1.0"

[dependencies]
aes = "0.8.4"
shared-pygamer = {path = "../../lib/shared-pygamer"}
