[package]
edition = "2021"
name = "rtic-count-sequence"
version = "0.1.0"

[dependencies]
shared-pygamer = {path = "../../lib/shared-pygamer", features = ["rtic"]}

[features]
clock1k = ["shared-pygamer/clock1k"]
clock32k = ["shared-pygamer/clock32k"]
systick = ["shared-pygamer/systick"]
