[package]
edition = "2021"
name = "hal-delay-ns"
version = "0.1.0"

[dependencies]
# TODO: This will not be needed when PR is merged
shared = {path = "../../lib/shared", features = ["hal-delay-ns-test"]}
shared-metro = {path = "../../lib/shared-metro", features = ["clock1k"]}
